### ISSUE TITLE
编译报错：warning 283: function declarator with no prototype

### ISSUE THREAD

**Issue by lgzcoollg** [haozewu/C51#8]
刚从kei转sdcc，请帮忙看下：

build的时候的提示：
<img width="639" alt="image" src="https://github.com/haozewu/C51/assets/48668011/40cfbe12-9c14-48d8-8be5-f866c4d75a47">

8051.h也报错
<img width="596" alt="image" src="https://github.com/haozewu/C51/assets/48668011/153ce005-4987-4b04-bbc7-59d4df8c8f51">

setting:
<img width="714" alt="image" src="https://github.com/haozewu/C51/assets/48668011/3d9c0301-cf21-4000-bc3c-7ad78face509">

**Comment by haozewu** [comment]
很多年不做这个了，你自己尝试一下吧。
